#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-uglifier
Version  : 3.0.0
Release  : 9
URL      : https://rubygems.org/downloads/uglifier-3.0.0.gem
Source0  : https://rubygems.org/downloads/uglifier-3.0.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rubygems-tasks

%description
# Uglifier
Ruby wrapper for [UglifyJS](https://github.com/mishoo/UglifyJS2) JavaScript compressor.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n uglifier-3.0.0
gem spec %{SOURCE0} -l --ruby > rubygem-uglifier.gemspec

%build
export LANG=C
gem build rubygem-uglifier.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
uglifier-3.0.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/uglifier-3.0.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/.document
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/.gitmodules
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/.rspec
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/.rubocop.yml
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/gemfiles/alaska
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/gemfiles/rubyracer
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/gemfiles/rubyrhino
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/lib/es5.js
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/lib/split.js
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/lib/uglifier.js
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/lib/uglifier.rb
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/lib/uglifier/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/lib/uglify.js
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/spec/source_map_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/spec/uglifier_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/uglifier-3.0.0/uglifier.gemspec
/usr/lib64/ruby/gems/2.3.0/specifications/uglifier-3.0.0.gemspec
