#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-uglifier
Version  : 2.7.2
Release  : 5
URL      : https://rubygems.org/downloads/uglifier-2.7.2.gem
Source0  : https://rubygems.org/downloads/uglifier-2.7.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-execjs
BuildRequires : rubygem-json
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rubygems-tasks
BuildRequires : rubygem-source_map

%description
# Uglifier [![Build Status](https://travis-ci.org/lautis/uglifier.svg?branch=master)](https://travis-ci.org/lautis/uglifier) [![Dependency Status](https://gemnasium.com/lautis/uglifier.svg)](https://gemnasium.com/lautis/uglifier)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n uglifier-2.7.2
gem spec %{SOURCE0} -l --ruby > rubygem-uglifier.gemspec

%build
gem build rubygem-uglifier.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
uglifier-2.7.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/uglifier-2.7.2.gem
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/Uglifier/cdesc-Uglifier.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/Uglifier/comment_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/Uglifier/comment_setting-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/Uglifier/compile-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/Uglifier/compile-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/Uglifier/compile_with_map-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/Uglifier/compile_with_map-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/Uglifier/compress-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/Uglifier/compressor_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/Uglifier/conditional_option-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/Uglifier/enclose_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/Uglifier/encode_regexp-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/Uglifier/mangle_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/Uglifier/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/Uglifier/output_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/Uglifier/parse_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/Uglifier/read_source-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/Uglifier/run_uglifyjs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/Uglifier/screw_ie8%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/Uglifier/source_map_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/Uglifier/uglifyjs_source-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/lib/page-es5_js.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/lib/page-split_js.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/page-CHANGELOG_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/page-CONTRIBUTING_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/page-LICENSE_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/uglifier-2.7.2/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/.document
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/.gitmodules
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/.rspec
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/.rubocop.yml
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/CHANGELOG.md
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/LICENSE.txt
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/README.md
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/gemfiles/alaska
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/gemfiles/rubyracer
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/gemfiles/rubyrhino
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/lib/es5.js
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/lib/split.js
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/lib/uglifier.rb
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/lib/uglifier/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/lib/uglify.js
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/spec/source_map_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/spec/uglifier_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/uglifier-2.7.2/uglifier.gemspec
/usr/lib64/ruby/gems/2.2.0/specifications/uglifier-2.7.2.gemspec
